### ISSUE TITLE
Replace status.json with content items in Kontent Project

### ISSUE THREAD

**Issue by micheltol** [kontent-ai/cli#14]
### Motivation
When keeping the state of the migrations not in the status.json file, it would be easier to implement migrations in a CICD pipeline. My suggestion would be to keep this state as close as possible to the project / environment and store it as separate content-type(s). 

### Proposed solution
If the CLI could figure out based on projected & environment what the current state of the migrations is it would be really easy to run the migrations in an automatic stateless deployment process without telling the CLI exactly what to migrate.
With the current implementation we need to keep the status.json in sync between different deployment-agents in our CICD pipeline which makes it really hard to implement

### Additional context
The proposed solution is heavily inspired by the EF Core Code first migration

**Comment by michalpaukert** [comment]
Hi,
have you considered to commit your status.json using your deployment agent?
I think this would be more realiable then store status.json into Kontent.

If this solution does not fit your usecase, please let me know or reopen the issue.
