### ISSUE TITLE
Use transpiled JS files with static HTML

### ISSUE THREAD

**Issue by jp2ld** [kontent-ai/cli#25]
### Motivation

This feature would allow people who use the https://github.com/Kentico/kontent-migrations-boilerplate to be able to reference the transpiled JS files using the <script> tag in HTML files. Thus API calls could be tested in the browser.

The transpiled JS files also need to be created in a seperate folder (could be named 'dist') by the CLI. The "outDir" config in TSCONFIG could be used, but it creates the error that "all source files must be in the same directory". 

### Additional context

The framework now supports just using the kontent cli to perform the migrations. This makes the user heavily dependant on the CLI to test all scenarios.

**Comment by winklertomas** [comment]
Hi @jp2ld, 

Kontent CLI is meant to be used on Node, thus it could not be used on the browser. I would recommend you to use MAPI directly.
