### ISSUE TITLE
Feat: Update @kentico/kontent-management

### ISSUE THREAD

**Issue by Enngage** [kontent-ai/cli#3]
### Motivation

Update `@kentico/kontent-management` dependency to version `0.3.2` which adds support for following endpoints:

- list/add/modify asset folders
- add/get/list webhooks endpoints
- project information endpoint
- single taxonomy item

and

+ adds ability to automatically retrieve all items from paging queries
+ contains few improvements to types and fixes certain models.

For list of changes see changelog at https://github.com/Kentico/kontent-management-sdk-js/blob/master/CHANGELOG.md

**Comment by michalpaukert** [comment]
updated in #1
