### ISSUE TITLE
Verify Migration consistency

### ISSUE THREAD

**Issue by Simply007** [kontent-ai/cli#33]
### Motivation

Currently, you can run all migrations (and possibly a range of them #32). It would be great t have some verification mechanism, that would notify you you have `order` property in migration properly in place - From `1` to `X`. 

### Proposed solution

Raise warning/exception if the migrations do not have a range being set properly.

**Comment by winklertomas** [comment]
the verification of the `order` was added within https://github.com/Kentico/kontent-cli/pull/32
