### ISSUE TITLE
[FR] Add option to disable error logging

### ISSUE THREAD

**Issue by bwlng** [kontent-ai/cli#35]
### Motivation

The CLI logs verbose errors to the command line and adds a lot of extra noise to the CLI output when errors are handled properly. This can be [disabled easily](https://github.com/Kentico/kontent-management-sdk-js/issues/53#issuecomment-957630786) when making requests using the JavaScript SDK.

```
const managementClient = new ManagementClient({
   apiKey: 'x',
   projectId: 'y',
   httpService: new HttpService({
      logErrorsToConsole: false
   })
});
```

The CLI configures it’s own [`httpService`](https://github.com/Kentico/kontent-cli/blob/109d945f01a8d3a5f55097bf9162b2f842995d73/src/managementClientFactory.ts#L17-L23) and doesn't allow additional options to be configured. The default info logged out is easy to confuse with an error in the migration script when infact the error is safely handled in the migration.

### Proposed solution

Add the ability to disable logging errors to the console through a param on the run command or when invoking `apiClient` so users can opt in to their own error handling.

### Additional context

A case where this is useful is when updating all language variants of an item with a new value and some items are translated and others aren’t, so they don't need to be updated and will return a 404 if you attempt to get data from the variant.

If logging were disabled and the following code were in a migration:

```
for (const language of languages.data.items) {
    try {
        const languageVariant = await apiClient.viewLanguageVariant()
            .byItemCodename("item_codename")
            .byLanguageId(language.id)
            .toPromise()

        // Item isn’t translated in this language
        if (!languageVariant) {
            return
        }
       
       // Do stuff and upsert language variant
    } catch(error) {
        console.log(error.message)
    }
}
```

Output would be:

```
    The requested variant '{id: cd571471-a7ec-4f9c-b5e5-421f10becf13}' of content item '{codename: item_codename}' was not found.
```

Instead of the verbose log containing the full response.

**Comment by winklertomas** [comment]
Hello, thank you for the tip on extending the content-cli functionality. I'll try to add an option for configuring HttpService, but I'll make it a bit more general so that you can configure "AxiosRequestConfig" in addition to "logsErrorsToConsole". I'll create a pull request within the next week.
