### ISSUE TITLE
Time stamp support for migrations

### ISSUE THREAD

**Issue by Simply007** [kontent-ai/cli#40]
### Motivation

Include the timestamp in the migration data contract.

### Proposed solution

Add an option to use this timestamp for orders.

### Additional context

Q: Validate to include the timestamp in the file name. (maybe as a custom extension and then use the filename instead of module property.
Q: Validate how to work with time ranges.

See: https://github.com/digital-detox/kontent-migration-cli/blob/main/src/lib/run.ts#L19-L33

**Comment by IvanKiral** [comment]
Hey @tommarshall, we have published the new alpha version which includes our solution for dealing with timestamps. I would like to ask you if you would like to give it a try and give us some feedback. 

PR for  the issue https://github.com/kontent-ai/cli/pull/45
Npm package: https://www.npmjs.com/package/@kontent-ai/cli/v/0.7.0-alpha.0
