### ISSUE TITLE
Change to projectId to environmentId and update to management-sdk v5

### ISSUE THREAD

**Issue by vincent-aviva** [kontent-ai/cli#50]
### Motivation

Currently the CLI uses management-sdk 3.1 but you already have v5 with new options in it.

### Proposed solution

Update dependency to version 5 and change project-id usage to environment-id

**Comment by Simply007** [comment]
Hello @vincent-aviva,

thanks for reaching out. This is a valid point. It also makes the CLI API clearer (i.e., for the `environment add` command).

We planned to accommodate the upgrade, but first, we wanted to finish up the feature batch added in versions from 0.7.0 to 0.7.3 such as timestamp support, custom implementation for status storage, and run&rollback migrations.

We will take a look at it and unify the approach and define version `^5.0.0` as a peer and adjust the public API to use the environment when necessary.

**Comment by winklertomas** [comment]
Hello @vincent-aviva ,
the new 0.8.1 version of CLI, which defines CMAPI SDK version ^5.0.0 as a peer and adjusts the public API to use the environment IDs has been released.
