### ISSUE TITLE
Backup command accepts projectId argument instead of environmentId

### ISSUE THREAD

**Issue by Nickm615** [kontent-ai/cli#55]
### Brief bug description

The kbm backup command should accept --environmentId according to documentation, but instead it accepts --projectId

### Expected behavior

The backup command should accept --environmentId

**Comment by Simply007** [comment]
I guess the latest version accepts environmentId according to: https://github.com/kontent-ai/cli/releases/tag/0.8.1

**Comment by Nickm615** [comment]
As far as I can tell my packages are up to date
![image](https://github.com/kontent-ai/cli/assets/86981780/d9d8d0d6-906d-4efe-9852-78d477d45c3c)

and I get the following error when running kbm backup
![image](https://github.com/kontent-ai/cli/assets/86981780/6a24a60f-ec5a-428d-b9e3-1ea4e7c9c862)

Maybe I am missing something?

**Comment by Simply007** [comment]
I guess you have different version installed globaly and locally. 


`kbm -v` , or `kbm --version` should show you global version and if you are in the node project `npx kbm -v`, or `npx kbp --version` should show you locally installed one.

**Comment by laststandjam** [comment]
I'm running into same issue could it be a problem with NPM distrubution? 

<img width="926" alt="image" src="https://github.com/kontent-ai/cli/assets/53449817/aafe4977-695d-4126-b42b-7ed2b60c414f">

**Comment by Simply007** [comment]
This repository is for Kontent CLI -> so all the commands it offers if through `kontent [argumens]`.

I missed this is a Kontent CLI repository - this issue should be raised in [Kontent Backup manager repo](https://github.com/kontent-ai/backup-manager-js).

It seems like the [Backup manager tool](https://github.com/kontent-ai/backup-manager-js) does not have the latest version released yet so it does not accept `environmentId`, as it is described in README on GitHub (not on npm) in the repository.

But this repository is a wrapper containing the Backup manager and accepting `environmentId` and translating it to KBM's old `projectId`: https://github.com/kontent-ai/cli/blob/master/src/cmds/backup.ts#L99

So please close this issue and raise a new one in the Kontent Backup manager. In the meantime, you can use the `kontent backup [argument]` commands for this repo until the new KBM is released.

**Comment by Nickm615** [comment]
You're right, originally I thought the issue was in the CLI but now I see its related to the backup manager. I'll close this issue and open it there instead.
