### ISSUE TITLE
Upgrade @kentico/kontent-management

### ISSUE THREAD

**Issue by chriscarrillo** [kontent-ai/cli#6]
### Motivation
`kontent-cli` has a dependency of `kontent-management` locked at version `0.3.13`. The `kontent-management` version is now at `0.3.17`. The `kontent-management` upgrade will fix linting issues for the `kontent-cli`.

### Proposed solution
Perhaps upgrade the `kontent-management` dependency or maybe it should be a peer dependency. 

Please let me know if I can provide any more details. Thank you!

**Comment by michalpaukert** [comment]
Hi, @chriscarrillo 
Thank you for your feedback, I created pull request #7  for this issue that will fix this problem.
Anyway we will try to react on kontent-management update more frequently.
